"""empty message

Revision ID: 87d653577e87
Revises: None
Create Date: 2016-03-20 13:06:51.172127

"""

# revision identifiers, used by Alembic.
revision = '87d653577e87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('app', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('app', 'node_id')
    op.drop_column('app', 'user_id')
    op.add_column('moudle', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('moudle', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('moudle', 'node_id')
    op.drop_column('moudle', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moudle', sa.Column('user_id', sa.VARCHAR(), nullable=True))
    op.add_column('moudle', sa.Column('node_id', sa.VARCHAR(), nullable=True))
    op.drop_column('moudle', 'name')
    op.drop_column('moudle', 'desc')
    op.add_column('app', sa.Column('user_id', sa.VARCHAR(), nullable=True))
    op.add_column('app', sa.Column('node_id', sa.VARCHAR(), nullable=True))
    op.drop_column('app', 'name')
    op.drop_column('app', 'desc')
    ### end Alembic commands ###
